# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mini.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_minigame(object):
    def setupUi(self, minigame):
        minigame.setObjectName("minigame")
        minigame.resize(394, 300)
        self.question = QtWidgets.QLabel(minigame)
        self.question.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.question.setObjectName("question")
        self.word = QtWidgets.QLabel(minigame)
        self.word.setGeometry(QtCore.QRect(20, 60, 371, 81))
        self.word.setObjectName("word")
        self.horizontalLayoutWidget = QtWidgets.QWidget(minigame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 169, 381, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.option_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.option_1.setObjectName("option_1")
        self.horizontalLayout.addWidget(self.option_1)
        self.option_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.option_2.setObjectName("option_2")
        self.horizontalLayout.addWidget(self.option_2)
        self.score = QtWidgets.QLabel(minigame)
        self.score.setGeometry(QtCore.QRect(284, 9, 91, 31))
        self.score.setObjectName("score")
        self.right_wrong = QtWidgets.QLabel(minigame)
        self.right_wrong.setGeometry(QtCore.QRect(20, 260, 151, 20))
        self.right_wrong.setObjectName("right_wrong")
        self.next = QtWidgets.QPushButton(minigame)
        self.next.setGeometry(QtCore.QRect(290, 260, 93, 28))
        self.next.setObjectName("next")

        self.retranslateUi(minigame)
        QtCore.QMetaObject.connectSlotsByName(minigame)

    def retranslateUi(self, minigame):
        _translate = QtCore.QCoreApplication.translate
        minigame.setWindowTitle(_translate("minigame", "Dialog"))
        self.question.setText(_translate("minigame", "TextLabel"))
        self.word.setText(_translate("minigame", "TextLabel"))
        self.option_1.setText(_translate("minigame", "PushButton"))
        self.option_2.setText(_translate("minigame", "PushButton"))
        self.score.setText(_translate("minigame", "TextLabel"))
        self.right_wrong.setText(_translate("minigame", "TextLabel"))
        self.next.setText(_translate("minigame", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    minigame = QtWidgets.QDialog()
    ui = Ui_minigame()
    ui.setupUi(minigame)
    minigame.show()
    sys.exit(app.exec_())
