# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcomeWindow(object):
    def setupUi(self, welcomeWindow):
        welcomeWindow.setObjectName("welcomeWindow")
        welcomeWindow.resize(380, 428)
        self.centralwidget = QtWidgets.QWidget(welcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 110, 351, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pdf = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pdf.setText("")
        self.pdf.setObjectName("pdf")
        self.gridLayout.addWidget(self.pdf, 0, 0, 1, 1)
        self.summarise_text = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.summarise_text.setText("")
        self.summarise_text.setObjectName("summarise_text")
        self.gridLayout.addWidget(self.summarise_text, 2, 0, 1, 1)
        self.mini_game = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mini_game.setText("")
        self.mini_game.setObjectName("mini_game")
        self.gridLayout.addWidget(self.mini_game, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        welcomeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(welcomeWindow)
        self.statusbar.setObjectName("statusbar")
        welcomeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(welcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(welcomeWindow)

    def retranslateUi(self, welcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        welcomeWindow.setWindowTitle(_translate("welcomeWindow", "GlossGen"))
        self.label.setText(_translate("welcomeWindow", "Welcome, drag and drop an image to continue."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    welcomeWindow = QtWidgets.QMainWindow()
    ui = Ui_welcomeWindow()
    ui.setupUi(welcomeWindow)
    welcomeWindow.show()
    sys.exit(app.exec_())
