# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'word_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(446, 300)
        self.google = QtWidgets.QPushButton(Dialog)
        self.google.setGeometry(QtCore.QRect(350, 10, 93, 28))
        self.google.setObjectName("google")
        self.word = QtWidgets.QLabel(Dialog)
        self.word.setGeometry(QtCore.QRect(10, 20, 211, 51))
        self.word.setObjectName("word")
        self.info = QtWidgets.QLabel(Dialog)
        self.info.setGeometry(QtCore.QRect(10, 90, 421, 201))
        self.info.setObjectName("info")
        self.bookmark = QtWidgets.QPushButton(Dialog)
        self.bookmark.setGeometry(QtCore.QRect(250, 10, 93, 28))
        self.bookmark.setObjectName("bookmark")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.google.setText(_translate("Dialog", "PushButton"))
        self.word.setText(_translate("Dialog", "TextLabel"))
        self.info.setText(_translate("Dialog", "TextLabel"))
        self.bookmark.setText(_translate("Dialog", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
